# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='fixtures.fixture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_fixtures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Fixture',
                'verbose_name_plural': 'Favorite Fixtures',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fixture')},
            },
        ),
    ]
