# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(choices=[('1X2', 'Resultado'), ('BTTS', 'Ambas Marcam'), ('OVER_25', 'Over 2.5 Gols'), ('OVER_15', 'Over 1.5 Gols'), ('AH', 'Asian Handicap'), ('ANY', 'Qualquer Mercado')], default='ANY', max_length=20)),
                ('minimum_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('any', 'Qualquer')], default='high', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
