# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('fixture_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('LIVE', 'Live'), ('HT', 'Half Time'), ('FT', 'Finished'), ('PST', 'Postponed'), ('CANC', 'Cancelled')], default='NS', max_length=10)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('round', models.CharField(blank=True, max_length=100)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='leagues.league')),
            ],
            options={
                'verbose_name': 'Fixture',
                'verbose_name_plural': 'Fixtures',
                'ordering': ['fixture_date'],
                'indexes': [models.Index(fields=['fixture_date', 'status'], name='fixtures_fi_fixture_e3fd8c_idx'), models.Index(fields=['league', 'fixture_date'], name='fixtures_fi_league__03aa90_idx')],
            },
        ),
    ]
