# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2024)),
                ('last_5_wins', models.IntegerField(default=0)),
                ('last_5_draws', models.IntegerField(default=0)),
                ('last_5_losses', models.IntegerField(default=0)),
                ('avg_goals_scored', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('avg_goals_conceded', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('both_teams_score_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('over25_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('over15_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('clean_sheet_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fail_to_score_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('home_avg_goals_scored', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('home_avg_goals_conceded', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('away_avg_goals_scored', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('away_avg_goals_conceded', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='leagues.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Statistics',
                'verbose_name_plural': 'Team Statistics',
                'unique_together': {('team', 'league', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=2024)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='teams.team')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['league', 'season', 'position'], name='statistics__league__d935e3_idx')],
                'unique_together': {('team', 'league', 'season')},
            },
        ),
    ]
