# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('market_label', models.CharField(blank=True, max_length=100)),
                ('probability', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('score', models.IntegerField(default=0)),
                ('confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='low', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fixtures.fixture')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['confidence', 'created_at'], name='analysis_pr_confide_636f61_idx')],
                'unique_together': {('fixture', 'market')},
            },
        ),
    ]
