# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('api_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bookmaker',
                'verbose_name_plural': 'Bookmakers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('1X2', '1X2 - Resultado'), ('BTTS', 'Ambas Marcam'), ('OVER_15', 'Over 1.5 Gols'), ('OVER_25', 'Over 2.5 Gols'), ('OVER_35', 'Over 3.5 Gols'), ('AH', 'Asian Handicap'), ('DC', 'Dupla Chance'), ('DNB', 'Draw No Bet')], max_length=20)),
                ('selection', models.CharField(max_length=100)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='odds.bookmaker')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='fixtures.fixture')),
            ],
            options={
                'verbose_name': 'Odd',
                'verbose_name_plural': 'Odds',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['fixture', 'market'], name='odds_odd_fixture_6a2250_idx'), models.Index(fields=['captured_at'], name='odds_odd_capture_ab1e76_idx')],
            },
        ),
    ]
