# Generated by Django 4.2.13 on 2026-05-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True)),
                ('season', models.IntegerField(default=2024)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['country', 'name'],
                'indexes': [models.Index(fields=['is_active', 'season'], name='leagues_lea_is_acti_1a9b4a_idx')],
            },
        ),
    ]
